

const BASE = [
    {
      id: 1,
      nombre: "Royal Leblon",
      descripcion: "Dos medallones de carne de 100gr. dos fetas de queso cheddar, panceta, cebolla caramelizada y salsa Leblon en pan brioche",
      img: "./assets/img/Royal.jpg",
      precio: 1190,
      cantidad: 1,
    },
    {
      id: 2,
      nombre: "Americana",
      descripcion: "Dos medallones de carne de 100gr. dos fetas de queso cheddar, tomate, lechuga, cebolla, pepinos, panceta y salsa Leblon en pan brioche",
      img: "./assets/img/americana.jpg",
      precio: 1190,
      cantidad: 1,
    },
    {
      id: 3,
      nombre: "Crispy",
      descripcion: "Dos medallones de carne de 100gr. dos fetas de queso cheddar, panceta, cebolla crispy y alioli en pan brioche",
      img: "./assets/img/crispy.jpg",
      precio: 1190,
      cantidad: 1,
    },
    {
      id: 4,
      nombre: "Doble Cuarto de Libra",
      descripcion: "Dos medallones de carne de 100gr. dos fetas de queso cheddar, cebolla cruda en bruniore, pepinos, ketchup y mostaza en pan brioche",
      img: "./assets/img/doble-cuarto-libra.jpg",
      precio: 990,
      cantidad: 1,
    },
    {
      id: 5,
      nombre: "Triple Leblon",
      descripcion: "Tres medallones de carne de 100gr. tres fetas de queso cheddar, panceta y salsa Leblon en pan brioche",
      img: "./assets/img/triple-leblon.jpg",
      precio: 1300,
      cantidad: 1,
    },
    {
      id: 6,
      nombre: "Doble Cheeseburger",
      descripcion: "Dos medallones de carne de 100gr. tres fetas de queso cheddar en pan brioche",
      img: "./assets/img/doble-cheseeburger.jpg",
      precio: 990,
      cantidad: 1,
    },
    {
      id: 7,
      nombre: "La de Roque",
      descripcion: "Dos medallones de carne de 100gr. una feta de queso marbled, queso azul, cebolla caramelizada, champignones salteados en manteca y rúcula en pan brioche",
      img: "./assets/img/Roque.jpg",
      precio: 1190,
      cantidad: 1,
    },
    {
      id: 8,
      nombre: "Veggie",
      descripcion: "Un medallon de vegatales Not Co, una feta de queso dambo, una feta de queso marbled, tomate, rúcula, cebolla caramelizada y champignones salteados en manteca en pan brioche",
      img: "./assets/img/veggie.jpg",
      precio: 1190,
      cantidad: 1,
    },
    {
      id: 9,
      nombre: "Papas Fritas",
      descripcion: "Porción de nuestras papas fritas clásicas",
      img: "./assets/img/papas-fritas.jpg",
      precio: 500,
      cantidad: 1,
    },
    {
      id: 10,
      nombre: "Papas Fritas con Cheddar y Panceta",
      descripcion: "Porción de nuestras clásicas papas fritas, bañadas en queso cheddar con lonjas de panceta",
      img: "./assets/img/papas-cheddar-panceta.jpg",
      precio: 700,
      cantidad: 1,
    },
    {
      id: 11,
      nombre: "APA Escalada",
      descripcion: "Tirada Artesanal - Pinta",
      img: "./assets/img/cerveza-apa.jpg",
      precio: 380,
      cantidad: 1,
    },
    {
      id: 12,
      nombre: "IPA Escalada",
      descripcion: "Tirada Artesanal - Pinta",
      img: "./assets/img/cerveza-ipa.jpg",
      precio: 380,
      cantidad: 1,
    },
    {
      id: 13,
      nombre: "Irish Escalada",
      descripcion: "Tirada Artesanal - Pinta",
      img: "./assets/img/cerveza-irish.jpg",
      precio: 380,
      cantidad: 1,
    },
    {
      id: 14,
      nombre: "Stout Beata",
      descripcion: "Tirada Artesanal - Pinta",
      img: "./assets/img/cerveza-stout.jpg",
      precio: 400,
      cantidad: 1,
    },
    {
      id: 15,
      nombre: "Le Blonde Escalada",
      descripcion: "Tirada Artesanal - Pinta",
      img: "./assets/img/cerveza-le-blonde.jpg",
      precio: 350,
      cantidad: 1,
    },
    {
      id: 16,
      nombre: "Gaseosa - Coca Cola/Sprite/Fanta",
      descripcion: "En botella Pet de 500ml",
      img: "./assets/img/gaseosa.jpg",
      precio: 270,
      cantidad: 1,
    },
  ];